name: Sword
version: '1.0-SNAPSHOT'
main: Swordsmp.sword.Sword
api-version: '1.20'

commands:
  givesword:
    description: Gives the specified sword to a player
    usage: /givesword <player> <sword_number>
    permission: sword.give # Add this line
    permission-message: "You do not have permission to use this command."
permissions:
  sword.give:
    description: Allows the use of the /givesword command
    default: op
